name: Node.js CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - run: npm ci
    - run: npm run build --if-present
    - name: run fetcher.js
      run: node fetcher.js `which firefox` > prefall.json
    - name: run surveyer.js
      run: |
        echo '[]' > /tmp/none.json
        node surveyer.js /tmp/none.json prefall.json > diff.html
    - name: Check generated files
      run: |
        ls -l
        [ -s prefall.json ] && [ -s diff.html ]
